package com.mimo.gstbilling.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.mimo.gstbilling.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EWayBillScreen(navController: NavController) {
    var invoiceNumber by remember { mutableStateOf("") }
    var transportMode by remember { mutableStateOf("Road") }
    var vehicleNumber by remember { mutableStateOf("") }
    var distance by remember { mutableStateOf("") }
    var fromState by remember { mutableStateOf("") }
    var toState by remember { mutableStateOf("") }
    var showTransportDropdown by remember { mutableStateOf(false) }
    var showGenerated by remember { mutableStateOf(false) }
    val transportModes = listOf("Road", "Rail", "Air", "Ship")

    if (showGenerated) {
        AlertDialog(onDismissRequest = { showGenerated = false },
            title = { Text("E-Way Bill Generated", fontWeight = FontWeight.Bold) },
            text = {
                Column {
                    Text("E-Way Bill No: ${System.currentTimeMillis() % 1000000000}", fontWeight = FontWeight.Bold, color = Primary, fontSize = 16.sp)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Valid for 24 hours from generation", fontSize = 12.sp, color = TextSecondary)
                }
            },
            confirmButton = { TextButton(onClick = { showGenerated = false; navController.popBackStack() }) { Text("OK") } }
        )
    }

    Scaffold(
        topBar = { TopAppBar(title = { Text("E-Way Bill", fontWeight = FontWeight.Bold) }, navigationIcon = { IconButton(onClick = { navController.popBackStack() }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back") } }, colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.White, titleContentColor = Color(0xFF1A1A1A), navigationIconContentColor = Color(0xFF1A1A1A))) }
    ) { padding ->
        Column(modifier = Modifier.fillMaxSize().padding(padding).background(Background).verticalScroll(rememberScrollState()).navigationBarsPadding()) {
            Card(modifier = Modifier.fillMaxWidth().padding(16.dp), shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = Color.White)) {
                Column(modifier = Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Transport Details", fontWeight = FontWeight.Bold, fontSize = 16.sp, color = TextPrimary)
                    OutlinedTextField(value = invoiceNumber, onValueChange = { invoiceNumber = it }, label = { Text("Invoice Number *") }, singleLine = true, modifier = Modifier.fillMaxWidth())
                    Box {
                        OutlinedTextField(value = transportMode, onValueChange = {}, readOnly = true, label = { Text("Transport Mode") }, trailingIcon = { Icon(Icons.Filled.ArrowDropDown, contentDescription = null, modifier = Modifier.clickable { showTransportDropdown = true }) }, modifier = Modifier.fillMaxWidth())
                        DropdownMenu(expanded = showTransportDropdown, onDismissRequest = { showTransportDropdown = false }) {
                            transportModes.forEach { m -> DropdownMenuItem(text = { Text(m) }, onClick = { transportMode = m; showTransportDropdown = false }) }
                        }
                    }
                    OutlinedTextField(value = vehicleNumber, onValueChange = { vehicleNumber = it }, label = { Text("Vehicle Number") }, singleLine = true, modifier = Modifier.fillMaxWidth())
                    OutlinedTextField(value = distance, onValueChange = { distance = it }, label = { Text("Distance (km)") }, singleLine = true, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), modifier = Modifier.fillMaxWidth())
                }
            }
            Card(modifier = Modifier.fillMaxWidth().padding(16.dp), shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = Color.White)) {
                Column(modifier = Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Location Details", fontWeight = FontWeight.Bold, fontSize = 16.sp, color = TextPrimary)
                    OutlinedTextField(value = fromState, onValueChange = { fromState = it }, label = { Text("From State *") }, singleLine = true, modifier = Modifier.fillMaxWidth())
                    OutlinedTextField(value = toState, onValueChange = { toState = it }, label = { Text("To State *") }, singleLine = true, modifier = Modifier.fillMaxWidth())
                }
            }
            Button(onClick = { showGenerated = true }, modifier = Modifier.fillMaxWidth().padding(16.dp).height(52.dp), shape = RoundedCornerShape(12.dp), colors = ButtonDefaults.buttonColors(containerColor = RedAccent), enabled = invoiceNumber.isNotBlank() && fromState.isNotBlank() && toState.isNotBlank()) {
                Icon(Icons.Filled.CheckCircle, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Generate E-Way Bill", fontWeight = FontWeight.Bold, fontSize = 16.sp)
            }
            Spacer(modifier = Modifier.height(16.dp))
        }
    }
}
