package com.mimo.gstbilling.utils

data class HsnEntry(
    val code: String,
    val description: String,
    val taxRate: Double,
    val category: String,
    val keywords: List<String> = emptyList()
)

object HsnDatabase {

    private val masterList: List<HsnEntry> = listOf(
        // ========== FOOD & BEVERAGES (0% - Nil Rated) ==========
        HsnEntry("0011", "Live animals", 0.0, "Agriculture", listOf("animal", "live", "cattle", "cow", "buffalo")),
        HsnEntry("0201", "Meat of bovine animals, fresh or chilled", 0.0, "Food", listOf("meat", "beef", "mutton")),
        HsnEntry("0202", "Meat of bovine animals, frozen", 0.0, "Food", listOf("meat", "frozen", "beef")),
        HsnEntry("0401", "Milk and cream", 0.0, "Food", listOf("milk", "cream", "dairy")),
        HsnEntry("0402", "Milk powder", 0.0, "Food", listOf("milk", "powder", "dairy")),
        HsnEntry("0403", "Yoghurt", 0.0, "Food", listOf("yoghurt", "curd", "dahi")),
        HsnEntry("0405", "Butter", 0.0, "Food", listOf("butter", "ghee", "dairy")),
        HsnEntry("0601", "Live plants", 0.0, "Agriculture", listOf("plant", "seed", "bulb")),
        HsnEntry("0701", "Potatoes", 0.0, "Food", listOf("potato", "aloo")),
        HsnEntry("0713", "Dried leguminous vegetables", 0.0, "Food", listOf("dal", "lentil", "pulse", "bean", "chana", "moong", "masoor")),
        HsnEntry("0801", "Coconuts", 0.0, "Food", listOf("coconut", "nariyal")),
        HsnEntry("0803", "Bananas", 0.0, "Food", listOf("banana", "kela")),
        HsnEntry("0806", "Grapes", 0.0, "Food", listOf("grape", "angoor")),
        HsnEntry("0901", "Coffee", 0.0, "Food", listOf("coffee", "beans")),
        HsnEntry("0902", "Tea", 0.0, "Food", listOf("tea", "chai", "green tea")),
        HsnEntry("1001", "Wheat", 0.0, "Food", listOf("wheat", "gehu", "atta")),
        HsnEntry("1006", "Rice", 0.0, "Food", listOf("rice", "chawal", "basmati")),
        HsnEntry("1101", "Wheat flour (Atta)", 0.0, "Food", listOf("atta", "flour", "maida", "wheat")),
        HsnEntry("1102", "Cereal flour", 0.0, "Food", listOf("flour", "maida", "suji")),
        HsnEntry("1701", "Sugar", 0.0, "Food", listOf("sugar", "cheeni", "jaggery", "gur")),
        HsnEntry("1905", "Bread, pastry", 5.0, "Food", listOf("bread", "roti", "naan", "biscuit")),
        HsnEntry("2106", "Food preparations n.e.s", 18.0, "Food", listOf("food", "mix", "masala", "spice mix")),
        HsnEntry("2201", "Mineral water", 18.0, "Food", listOf("water", "mineral", "bottle")),
        HsnEntry("2202", "Aerated drinks", 28.0, "Food", listOf("cold drink", "soda", "cola", "sprite", "pepsi", "coke")),
        HsnEntry("2203", "Beer", 28.0, "Food", listOf("beer", "alcohol")),
        HsnEntry("2204", "Wine", 28.0, "Food", listOf("wine", "grape wine")),
        HsnEntry("2208", "Spirituous liquors", 28.0, "Food", listOf("whisky", "rum", "vodka", "brandy", "spirit", "alcohol")),
        HsnEntry("2301", "Oil cake", 0.0, "Agriculture", listOf("oil cake", "meal")),

        // ========== GST 5% ==========
        HsnEntry("0710", "Frozen vegetables", 5.0, "Food", listOf("frozen", "vegetable", "peas", "corn")),
        HsnEntry("0711", "Pickled vegetables", 5.0, "Food", listOf("pickle", "achar", "olive")),
        HsnEntry("0805", "Citrus fruits", 5.0, "Food", listOf("orange", "lemon", "nimbu", "mosambi")),
        HsnEntry("0810", "Other fruits", 5.0, "Food", listOf("fruit", "apple", "mango")),
        HsnEntry("1005", "Maize (Corn)", 0.0, "Food", listOf("maize", "corn", "makka")),
        HsnEntry("1008", "Other cereals", 0.0, "Food", listOf("jowar", "bajra", "ragi", "millet")),
        HsnEntry("1104", "Cereal flakes", 5.0, "Food", listOf("cornflakes", "oats", "cereal")),
        HsnEntry("1201", "Soya beans", 0.0, "Agriculture", listOf("soya", "soybean")),
        HsnEntry("1202", "Groundnuts", 0.0, "Food", listOf("groundnut", "peanut", "moongphali")),
        HsnEntry("1507", "Soyabean oil", 5.0, "Food", listOf("oil", "soyabean", "cooking")),
        HsnEntry("1508", "Groundnut oil", 5.0, "Food", listOf("oil", "groundnut", "peanut")),
        HsnEntry("1509", "Olive oil", 5.0, "Food", listOf("oil", "olive")),
        HsnEntry("1511", "Palm oil", 5.0, "Food", listOf("oil", "palm")),
        HsnEntry("1512", "Sunflower oil", 5.0, "Food", listOf("oil", "sunflower", "sursur tel")),
        HsnEntry("1513", "Coconut oil", 5.0, "Food", listOf("oil", "coconut", "nariyal tel")),
        HsnEntry("1514", "Mustard oil", 5.0, "Food", listOf("oil", "mustard", "sarson tel")),
        HsnEntry("1517", "Ghee", 5.0, "Food", listOf("ghee", "butter oil")),
        HsnEntry("1704", "Confectionery", 5.0, "Food", listOf("candy", "sweet", "toffee", "chocolate", "halwa")),
        HsnEntry("1806", "Chocolate", 5.0, "Food", listOf("chocolate", "dairy milk", "kitkat")),
        HsnEntry("1904", "Ready to eat food", 5.0, "Food", listOf("maggie", "noodles", "pasta", "ready to eat")),
        HsnEntry("2002", "Tomato preparations", 5.0, "Food", listOf("tomato", "ketchup", "sauce")),
        HsnEntry("2009", "Fruit juices", 5.0, "Food", listOf("juice", "frooti", "real")),
        HsnEntry("2101", "Tea extracts", 5.0, "Food", listOf("tea", "extract", "instant")),
        HsnEntry("2102", "Yeasts", 5.0, "Food", listOf("yeast", "baking")),
        HsnEntry("2103", "Sauces", 5.0, "Food", listOf("sauce", "soy sauce", "tomato sauce")),
        HsnEntry("2104", "Soup preparations", 5.0, "Food", listOf("soup", "broth")),
        HsnEntry("2105", "Ice cream", 5.0, "Food", listOf("ice cream", "kulfi")),
        HsnEntry("2302", "Bran", 5.0, "Food", listOf("bran", "husk")),
        HsnEntry("2306", "Oil seed residue", 5.0, "Agriculture", listOf("oil cake", "residue")),

        // ========== CLOTHING & TEXTILES (5%) ==========
        HsnEntry("5004", "Silk fabric", 5.0, "Clothing", listOf("silk", "fabric", "cloth")),
        HsnEntry("5005", "Yarn of silk", 5.0, "Clothing", listOf("silk", "yarn")),
        HsnEntry("5201", "Cotton, not carded or combed", 5.0, "Clothing", listOf("cotton", "raw cotton")),
        HsnEntry("5208", "Woven cotton fabrics", 5.0, "Clothing", listOf("cotton", "fabric", "cloth", "cotton fabric")),
        HsnEntry("5407", "Synthetic filament yarn fabrics", 5.0, "Clothing", listOf("polyester", "nylon", "synthetic")),
        HsnEntry("6101", "Men's overcoats (knitted)", 5.0, "Clothing", listOf("coat", "jacket", "men")),
        HsnEntry("6102", "Women's overcoats (knitted)", 5.0, "Clothing", listOf("coat", "jacket", "women")),
        HsnEntry("6103", "Men's suits, trousers (knitted)", 5.0, "Clothing", listOf("suit", "trouser", "pant", "men")),
        HsnEntry("6104", "Women's suits (knitted)", 5.0, "Clothing", listOf("suit", "saree", "women")),
        HsnEntry("6105", "Men's shirts (knitted)", 5.0, "Clothing", listOf("shirt", "men", "half sleeve", "full sleeve")),
        HsnEntry("6106", "Women's blouses (knitted)", 5.0, "Clothing", listOf("blouse", "women", "kurti")),
        HsnEntry("6107", "Men's undergarments (knitted)", 5.0, "Clothing", listOf("underwear", "vest", "baniyan", "men")),
        HsnEntry("6108", "Women's undergarments (knitted)", 5.0, "Clothing", listOf("inner", "women", "petticoat")),
        HsnEntry("6109", "T-shirts, singlets (knitted)", 5.0, "Clothing", listOf("tshirt", "t-shirt", "vest", "singlet")),
        HsnEntry("6110", "Sweaters, shawls (knitted)", 5.0, "Clothing", listOf("sweater", "shawl", "cardigan")),
        HsnEntry("6111", "Babies' garments (knitted)", 5.0, "Clothing", listOf("baby", "kids", "children")),
        HsnEntry("6112", "Track suits (knitted)", 5.0, "Clothing", listOf("tracksuit", "sportswear")),
        HsnEntry("6201", "Men's overcoats (woven)", 5.0, "Clothing", listOf("coat", "blazer", "men")),
        HsnEntry("6202", "Women's overcoats (woven)", 5.0, "Clothing", listOf("coat", "women")),
        HsnEntry("6203", "Men's suits, trousers (woven)", 5.0, "Clothing", listOf("suit", "trouser", "pant", "men")),
        HsnEntry("6204", "Women's suits (woven)", 5.0, "Clothing", listOf("suit", "women", "skirt")),
        HsnEntry("6205", "Men's shirts (woven)", 5.0, "Clothing", listOf("shirt", "men", "formal")),
        HsnEntry("6206", "Women's blouses (woven)", 5.0, "Clothing", listOf("blouse", "women")),
        HsnEntry("6211", "Track suits, ski suits (woven)", 5.0, "Clothing", listOf("tracksuit", "sportswear")),
        HsnEntry("6301", "Blankets, travelling rugs", 5.0, "Clothing", listOf("blanket", "quilt", "razai")),
        HsnEntry("6302", "Bed linen, table linen", 5.0, "Clothing", listOf("bedsheet", "pillow", "towel", "tablecloth")),
        HsnEntry("6305", "Sacks and bags", 5.0, "Clothing", listOf("sack", "bag", "gunny")),

        // ========== FOOTWEAR (5%) ==========
        HsnEntry("6401", "Waterproof footwear", 5.0, "Footwear", listOf("shoe", "boot", "slipper", "chappal")),
        HsnEntry("6402", "Other footwear", 5.0, "Footwear", listOf("shoe", "sneaker", "sport shoe")),
        HsnEntry("6403", "Leather footwear", 5.0, "Footwear", listOf("leather", "shoe", "formal", "boot")),
        HsnEntry("6404", "Textile footwear", 5.0, "Footwear", listOf("shoe", "canvas", "cloth shoe")),
        HsnEntry("6405", "Other footwear", 5.0, "Footwear", listOf("slipper", "flip flop", "chappal")),

        // ========== HANDICRAFTS & ARTISAN ==========
        HsnEntry("4202", "Trunks, suitcases", 5.0, "Accessories", listOf("bag", "suitcase", "luggage", "trunk", "trolley")),
        HsnEntry("4203", "Leather articles", 5.0, "Accessories", listOf("belt", "wallet", "purse", "leather")),
        HsnEntry("4421", "Wood articles", 5.0, "Handicraft", listOf("wood", "furniture", "wooden")),
        HsnEntry("4601", "Bamboo articles", 5.0, "Handicraft", listOf("bamboo", "cane", "wicker")),
        HsnEntry("5701", "Carpets", 5.0, "Handicraft", listOf("carpet", "rug", "dhurrie")),
        HsnEntry("5702", "Mats", 5.0, "Handicraft", listOf("mat", "doormat", "carpet")),
        HsnEntry("7018", "Glass beads", 5.0, "Handicraft", listOf("glass", "bead", "bangle")),
        HsnEntry("9601", "Worked ivory", 5.0, "Handicraft", listOf("ivory", "bone")),
        HsnEntry("9602", "Worked vegetable material", 5.0, "Handicraft", listOf("shell", "horn")),
        HsnEntry("9603", "Brooms", 5.0, "Handicraft", listOf("broom", "jhadu")),
        HsnEntry("9604", "Hand sieves", 5.0, "Handicraft", listOf("sieve", "chalni")),
        HsnEntry("9605", "Sewing kits", 5.0, "Handicraft", listOf("sewing", "needle", "thread")),
        HsnEntry("9606", "Buttons", 5.0, "Handicraft", listOf("button", "press button")),
        HsnEntry("9607", "Zippers", 5.0, "Handicraft", listOf("zipper", "zip")),
        HsnEntry("9608", "Pens, pencils", 5.0, "Handicraft", listOf("pen", "pencil", "marker")),
        HsnEntry("9612", "Typewriter ribbons", 5.0, "Handicraft", listOf("ribbon", "cartridge")),
        HsnEntry("9613", "Cigarette lighters", 5.0, "Handicraft", listOf("lighter")),
        HsnEntry("9615", "Combs, hair slides", 5.0, "Handicraft", listOf("comb", "hair clip")),
        HsnEntry("9616", "Scent sprays", 5.0, "Handicraft", listOf("perfume", "spray", "deodorant")),
        HsnEntry("9617", "Vacuum flasks", 5.0, "Handicraft", listOf("thermos", "flask", "bottle")),
        HsnEntry("9618", "Tailors' dummies", 5.0, "Handicraft", listOf("mannequin")),
        HsnEntry("9619", "Sanitary towels", 5.0, "Handicraft", listOf("pad", "napkin", "sanitary")),

        // ========== GST 12% ==========
        HsnEntry("0406", "Cheese", 12.0, "Food", listOf("cheese", "paneer")),
        HsnEntry("1901", "Food for infants", 12.0, "Food", listOf("baby food", "cerelac", "lactogen")),
        HsnEntry("2201", "Mineral water (packaged)", 12.0, "Food", listOf("water", "bisleri", "kinley")),
        HsnEntry("3304", "Beauty preparations", 12.0, "Cosmetics", listOf("cream", "lotion", "face wash", "beauty")),
        HsnEntry("3305", "Hair preparations", 12.0, "Cosmetics", listOf("shampoo", "conditioner", "hair oil", "hair dye")),
        HsnEntry("3306", "Dental preparations", 12.0, "Cosmetics", listOf("toothpaste", "toothbrush", "mouthwash")),
        HsnEntry("3401", "Soap", 12.0, "Cosmetics", listOf("soap", "body wash", "handwash")),
        HsnEntry("3402", "Detergents", 12.0, "Cosmetics", listOf("detergent", "surf", "washing powder")),
        HsnEntry("4015", "Rubber gloves", 12.0, "Rubber", listOf("glove", "rubber")),
        HsnEntry("4818", "Toilet paper", 12.0, "Stationery", listOf("tissue", "toilet paper", "napkin")),
        HsnEntry("4819", "Cartons, boxes", 12.0, "Stationery", listOf("box", "carton", "packaging")),
        HsnEntry("4820", "Registers, notebooks", 12.0, "Stationery", listOf("notebook", "register", "copy")),
        HsnEntry("4823", "Paper articles n.e.s.", 12.0, "Stationery", listOf("paper", "envelope", "card")),
        HsnEntry("6304", "Other furnishing articles", 12.0, "Clothing", listOf("curtain", "cushion", "furnishing")),
        HsnEntry("8517", "Telephones, smartphones", 12.0, "Electronics", listOf("phone", "mobile", "smartphone", "iphone", "samsung")),
        HsnEntry("8518", "Microphones, speakers", 12.0, "Electronics", listOf("speaker", "headphone", "earphone", "mic")),
        HsnEntry("9401", "Seats, chairs", 12.0, "Furniture", listOf("chair", "sofa", "seat", "stool", "bench")),
        HsnEntry("9403", "Other furniture", 12.0, "Furniture", listOf("table", "desk", "shelf", "cupboard", "almirah", "bed", "furniture")),
        HsnEntry("9404", "Mattress, cushions", 12.0, "Furniture", listOf("mattress", "cushion", "pillow")),
        HsnEntry("9610", "Chalk", 12.0, "Stationery", listOf("chalk", "whiteboard")),

        // ========== GST 18% ==========
        HsnEntry("3004", "Medicines", 18.0, "Pharma", listOf("medicine", "tablet", "capsule", "syrup", "drug", "paracetamol", "antibiotic")),
        HsnEntry("3005", "Bandages, dressings", 18.0, "Pharma", listOf("bandage", "dressing", "plaster")),
        HsnEntry("3006", "Pharmaceutical goods", 18.0, "Pharma", listOf("pharmaceutical", "medical")),
        HsnEntry("3213", "Artists' colours", 18.0, "Stationery", listOf("paint", "colour", "art")),
        HsnEntry("3301", "Essential oils", 18.0, "Chemical", listOf("oil", "essential", "perfume")),
        HsnEntry("3303", "Perfumes", 18.0, "Cosmetics", listOf("perfume", "cologne", "attar")),
        HsnEntry("3307", "Deodorants", 18.0, "Cosmetics", listOf("deodorant", "perfume", "spray")),
        HsnEntry("3918", "Plastic articles", 18.0, "Plastic", listOf("plastic", "pvc", "pipe")),
        HsnEntry("3919", "Self-adhesive plastics", 18.0, "Plastic", listOf("tape", "sticker", "label")),
        HsnEntry("3920", "Plastic sheets", 18.0, "Plastic", listOf("sheet", "film", "plastic")),
        HsnEntry("3921", "Other plastic articles", 18.0, "Plastic", listOf("plastic", "container")),
        HsnEntry("3922", "Plastic bottles", 18.0, "Plastic", listOf("bottle", "container", "plastic")),
        HsnEntry("3923", "Plastic tableware", 18.0, "Plastic", listOf("plate", "glass", "tumbler", "plastic")),
        HsnEntry("3924", "Plastic household articles", 18.0, "Plastic", listOf("bucket", "mug", "bottle", "plastic")),
        HsnEntry("4011", "New pneumatic tyres", 18.0, "Automobile", listOf("tyre", "tire", "wheel")),
        HsnEntry("4013", "Rubber tubes", 18.0, "Rubber", listOf("tube", "rubber")),
        HsnEntry("4202", "Leather bags, cases", 18.0, "Accessories", listOf("bag", "handbag", "briefcase")),
        HsnEntry("4407", "Sawn wood", 18.0, "Timber", listOf("wood", "plywood", "timber", "plank")),
        HsnEntry("4408", "Wood veneer", 18.0, "Timber", listOf("veneer", "plywood")),
        HsnEntry("4411", "Fibreboard", 18.0, "Timber", listOf("mdf", "plywood", "board")),
        HsnEntry("4412", "Plywood", 18.0, "Timber", listOf("plywood", "ply", "bison panel")),
        HsnEntry("4802", "Uncoated paper", 18.0, "Stationery", listOf("paper", "printing paper", "a4")),
        HsnEntry("4810", "Coated paper", 18.0, "Stationery", listOf("photo paper", "coated")),
        HsnEntry("4811", "Paper laminated", 18.0, "Stationery", listOf("laminated", "sticker")),
        HsnEntry("4813", "Cigarette paper", 18.0, "Stationery", listOf("cigarette", "rolling")),
        HsnEntry("4817", "Envelopes", 18.0, "Stationery", listOf("envelope", "letter")),
        HsnEntry("4821", "Paper labels", 18.0, "Stationery", listOf("label", "sticker")),
        HsnEntry("4901", "Printed books", 18.0, "Stationery", listOf("book", "novel", "textbook")),
        HsnEntry("4902", "Newspapers", 18.0, "Stationery", listOf("newspaper", "magazine", "journal")),
        HsnEntry("4907", "Stamps, cheque books", 18.0, "Stationery", listOf("stamp", "cheque", "postal")),
        HsnEntry("4908", "Transfers (decalcomanias)", 18.0, "Stationery", listOf("transfer", "sticker")),
        HsnEntry("4909", "Printed cards", 18.0, "Stationery", listOf("greeting card", "postcard", "wedding card")),
        HsnEntry("4910", "Calendars", 18.0, "Stationery", listOf("calendar", "diary")),
        HsnEntry("4911", "Printed matter n.e.s.", 18.0, "Stationery", listOf("brochure", "pamphlet", "catalogue")),
        HsnEntry("5208", "Cotton fabrics", 18.0, "Textile", listOf("cotton", "fabric", "cloth")),
        HsnEntry("5402", "Synthetic yarn", 18.0, "Textile", listOf("polyester", "yarn", "nylon")),
        HsnEntry("5403", "Artificial yarn", 18.0, "Textile", listOf("yarn", "viscose")),
        HsnEntry("5404", "Synthetic monofilament", 18.0, "Textile", listOf("fishing line", "monofilament")),
        HsnEntry("5405", "Artificial monofilament", 18.0, "Textile", listOf("thread", "yarn")),
        HsnEntry("5509", "Yarn of staple fibre", 18.0, "Textile", listOf("yarn", "cotton yarn", "polyester yarn")),
        HsnEntry("5510", "Yarn of artificial staple fibre", 18.0, "Textile", listOf("yarn", "rayon")),
        HsnEntry("5801", "Woven pile fabrics", 18.0, "Textile", listOf("velvet", "terry")),
        HsnEntry("5901", "Rubberised textile", 18.0, "Textile", listOf("raincoat", "oilcloth")),
        HsnEntry("5903", "Textile fabrics, impregnated", 18.0, "Textile", listOf("laminated", "coated")),
        HsnEntry("5906", "Adhesive textile tape", 18.0, "Textile", listOf("tape", "fabric tape")),
        HsnEntry("5907", "Textile fabrics, coated", 18.0, "Textile", listOf("coated", "canvas")),
        HsnEntry("5911", "Technical textile articles", 18.0, "Textile", listOf("filter", "conveyor")),
        HsnEntry("6001", "Knitted pile fabrics", 18.0, "Textile", listOf("fleece", "terry")),
        HsnEntry("6002", "Knitted fabrics", 18.0, "Textile", listOf("jersey", "knit")),
        HsnEntry("6003", "Other knitted fabrics", 18.0, "Textile", listOf("fabric", "mesh")),
        HsnEntry("6004", "Knitted fabrics >30cm wide", 18.0, "Textile", listOf("fabric", "wide")),
        HsnEntry("6005", "Warp knitted fabrics", 18.0, "Textile", listOf("lace", "net")),
        HsnEntry("6006", "Other knitted fabrics", 18.0, "Textile", listOf("knit", "fabric")),
        HsnEntry("6115", "Stockings, socks (knitted)", 18.0, "Clothing", listOf("sock", "stocking", "pantyhose")),
        HsnEntry("6116", "Gloves (knitted)", 18.0, "Clothing", listOf("glove", "hand glove")),
        HsnEntry("6117", "Other made up clothing (knitted)", 18.0, "Clothing", listOf("scarf", "muffler", "tie")),
        HsnEntry("6212", "Brassieres, girdles", 18.0, "Clothing", listOf("bra", "corset", "girdle")),
        HsnEntry("6213", "Handkerchiefs", 18.0, "Clothing", listOf("handkerchief", "hanky")),
        HsnEntry("6214", "Shawls, scarves (woven)", 18.0, "Clothing", listOf("shawl", "scarf", "stole")),
        HsnEntry("6215", "Cufflinks, ties (woven)", 18.0, "Clothing", listOf("tie", "cufflink", "bow tie")),
        HsnEntry("6216", "Gloves (woven)", 18.0, "Clothing", listOf("glove", "hand glove")),
        HsnEntry("6217", "Other clothing accessories (woven)", 18.0, "Clothing", listOf("apron", "sash")),
        HsnEntry("6307", "Other made up textile articles", 18.0, "Clothing", listOf("mask", "flag", "banner")),
        HsnEntry("6406", "Parts of footwear", 18.0, "Footwear", listOf("sole", "heel", "insole")),
        HsnEntry("6501", "Hat bodies", 18.0, "Clothing", listOf("hat", "cap", "topi")),
        HsnEntry("6505", "Hats (knitted)", 18.0, "Clothing", listOf("hat", "cap", "beanie")),
        HsnEntry("6506", "Other headgear", 18.0, "Clothing", listOf("helmet", "hat", "cap")),
        HsnEntry("6507", "Head-bands, linings", 18.0, "Clothing", listOf("headband", "cap lining")),
        HsnEntry("6601", "Umbrellas", 18.0, "Clothing", listOf("umbrella", "parasol")),
        HsnEntry("6602", "Walking sticks", 18.0, "Clothing", listOf("stick", "cane")),
        HsnEntry("6701", "Skins of birds", 18.0, "Clothing", listOf("feather", "down")),
        HsnEntry("6702", "Artificial flowers", 18.0, "Clothing", listOf("flower", "artificial")),
        HsnEntry("6703", "Human hair", 18.0, "Clothing", listOf("wig", "hair")),
        HsnEntry("6704", "Wigs", 18.0, "Clothing", listOf("wig", "hair piece")),

        // ========== ELECTRONICS & APPLIANCES (18%) ==========
        HsnEntry("8414", "Air pumps, compressors", 18.0, "Appliance", listOf("pump", "compressor", "vacuum")),
        HsnEntry("8415", "Air conditioning machines", 18.0, "Appliance", listOf("ac", "air conditioner", "split ac", "window ac")),
        HsnEntry("8418", "Refrigerators, freezers", 18.0, "Appliance", listOf("fridge", "refrigerator", "freezer", "deep freeze")),
        HsnEntry("8419", "Machinery for treatment of material", 18.0, "Appliance", listOf("heater", "sterilizer")),
        HsnEntry("8421", "Centrifuges, filters", 18.0, "Appliance", listOf("filter", "centrifuge", "water purifier")),
        HsnEntry("8422", "Dish washing machines", 18.0, "Appliance", listOf("dishwasher", "dish wash")),
        HsnEntry("8423", "Weighing machines", 18.0, "Appliance", listOf("scale", "weighing", "balance")),
        HsnEntry("8424", "Spray guns", 18.0, "Appliance", listOf("spray", "paint gun")),
        HsnEntry("8425", "Pulley blocks, winches", 18.0, "Appliance", listOf("pulley", "winch", "hoist")),
        HsnEntry("8426", "Cranes, lorries", 18.0, "Appliance", listOf("crane", "lorry")),
        HsnEntry("8427", "Fork-lift trucks", 18.0, "Appliance", listOf("forklift", "truck")),
        HsnEntry("8428", "Lifting machinery", 18.0, "Appliance", listOf("elevator", "lift", "conveyor")),
        HsnEntry("8429", "Self-propelled bulldozers", 18.0, "Appliance", listOf("bulldozer", "grader")),
        HsnEntry("8430", "Pile drivers, earth moving", 18.0, "Appliance", listOf("excavator", "earth mover")),
        HsnEntry("8431", "Parts for machinery", 18.0, "Appliance", listOf("part", "spare", "gear")),
        HsnEntry("8432", "Agricultural machinery", 18.0, "Appliance", listOf("plough", "harrow", "seed drill")),
        HsnEntry("8433", "Harvesting machinery", 18.0, "Appliance", listOf("harvester", "reaper", "thresher")),
        HsnEntry("8434", "Milking machines", 18.0, "Appliance", listOf("milking", "dairy")),
        HsnEntry("8435", "Presses, crushers (agri)", 18.0, "Appliance", listOf("press", "crusher")),
        HsnEntry("8436", "Other agricultural machinery", 18.0, "Appliance", listOf("sprayer", "agriculture")),
        HsnEntry("8437", "Seed sorting machines", 18.0, "Appliance", listOf("seed", "sorting")),
        HsnEntry("8438", "Food processing machinery", 18.0, "Appliance", listOf("food processing", "grinder", "mixer grinder")),
        HsnEntry("8439", "Pulp making machinery", 18.0, "Appliance", listOf("paper", "pulp")),
        HsnEntry("8440", "Bookbinding machinery", 18.0, "Appliance", listOf("binding", "book")),
        HsnEntry("8441", "Paper cutting machines", 18.0, "Appliance", listOf("paper cutting", "guillotine")),
        HsnEntry("8442", "Printing machinery", 18.0, "Appliance", listOf("printer", "printing press")),
        HsnEntry("8443", "Printers, copiers", 18.0, "Electronics", listOf("printer", "copier", "scanner", "photocopier")),
        HsnEntry("8444", "Textile machinery", 18.0, "Appliance", listOf("spinning", "weaving", "textile")),
        HsnEntry("8445", "Fibre preparing machines", 18.0, "Appliance", listOf("carding", "combing")),
        HsnEntry("8446", "Weaving machines", 18.0, "Appliance", listOf("loom", "weaving")),
        HsnEntry("8447", "Knitting machines", 18.0, "Appliance", listOf("knitting", "hosiery")),
        HsnEntry("8448", "Textile auxiliary machines", 18.0, "Appliance", listOf("textile", "auxiliary")),
        HsnEntry("8449", "Felt making machines", 18.0, "Appliance", listOf("felt", "nonwoven")),
        HsnEntry("8450", "Washing machines", 18.0, "Appliance", listOf("washing machine", "washing", "semi automatic", "fully automatic")),
        HsnEntry("8451", "Dry cleaning machines", 18.0, "Appliance", listOf("dry cleaning", "iron", "press")),
        HsnEntry("8452", "Sewing machines", 18.0, "Appliance", listOf("sewing machine", "stitching machine", "tailor")),
        HsnEntry("8459", "Machine tools", 18.0, "Appliance", listOf("lathe", "drilling", "milling")),
        HsnEntry("8460", "Grinding machines", 18.0, "Appliance", listOf("grinder", "grinding", "sharpener")),
        HsnEntry("8461", "Planing, shaving machines", 18.0, "Appliance", listOf("planing", "shaving")),
        HsnEntry("8462", "Forging, pressing machines", 18.0, "Appliance", listOf("press", "forge", "stamp")),
        HsnEntry("8463", "Metal working machines", 18.0, "Appliance", listOf("turning", "filing", "deburring")),
        HsnEntry("8464", "Stone working machines", 18.0, "Appliance", listOf("stone", "marble", "granite")),
        HsnEntry("8465", "Wood working machines", 18.0, "Appliance", listOf("wood", "sawing", "planing")),
        HsnEntry("8466", "Parts for machine tools", 18.0, "Appliance", listOf("tool holder", "chuck", "collet")),
        HsnEntry("8467", "Hand tools, pneumatic", 18.0, "Appliance", listOf("drill", "grinder", "saw", "pneumatic")),
        HsnEntry("8468", "Soldering, brazing machines", 18.0, "Appliance", listOf("soldering", "welding")),
        HsnEntry("8470", "Calculating machines", 18.0, "Electronics", listOf("calculator", "adding machine")),
        HsnEntry("8471", "Computers, laptops", 18.0, "Electronics", listOf("computer", "laptop", "desktop", "server", "macbook", "dell", "hp", "lenovo")),
        HsnEntry("8472", "Office machines", 18.0, "Electronics", listOf("typewriter", "hole punch", "stapler")),
        HsnEntry("8473", "Parts for office machines", 18.0, "Electronics", listOf("keyboard", "mouse", "monitor", "ram", "hard disk", "ssd")),
        HsnEntry("8474", "Sorting, screening machines", 18.0, "Appliance", listOf("screen", "classifier")),
        HsnEntry("8475", "Electric filament lamps", 18.0, "Electronics", listOf("bulb", "lamp", "tube light", "led")),
        HsnEntry("8476", "ATM machines", 18.0, "Electronics", listOf("atm", "vending")),
        HsnEntry("8477", "Rubber/plastics machinery", 18.0, "Appliance", listOf("injection moulding", "extrusion")),
        HsnEntry("8478", "Cigarette making machines", 18.0, "Appliance", listOf("cigarette", "tobacco")),
        HsnEntry("8479", "Industrial robots, machines", 18.0, "Appliance", listOf("robot", "industrial", "machine")),
        HsnEntry("8480", "Moulding boxes", 18.0, "Appliance", listOf("mould", "mold")),
        HsnEntry("8481", "Taps, cocks, valves", 18.0, "Appliance", listOf("tap", "valve", "faucet", "stop cock", "lever")),
        HsnEntry("8482", "Ball, roller bearings", 18.0, "Appliance", listOf("bearing", "ball bearing", "roller")),
        HsnEntry("8483", "Gears, gearboxes", 18.0, "Appliance", listOf("gear", "shaft", "coupling", "chain", "sprocket")),
        HsnEntry("8484", "Gaskets, washers", 18.0, "Appliance", listOf("gasket", "washer", "seal")),
        HsnEntry("8485", "Machinery parts n.e.s.", 18.0, "Appliance", listOf("part", "nozzle", "mandrel")),
        HsnEntry("8501", "Electric motors", 18.0, "Electronics", listOf("motor", "fan motor", "pump motor")),
        HsnEntry("8502", "Electric generators", 18.0, "Electronics", listOf("generator", "genset", "inverter")),
        HsnEntry("8503", "Parts for motors/generators", 18.0, "Electronics", listOf("rotor", "stator", "armature")),
        HsnEntry("8504", "Transformers, power supplies", 18.0, "Electronics", listOf("transformer", "adapter", "charger", "power supply", "ups", "inverter")),
        HsnEntry("8505", "Electromagnets, magnets", 18.0, "Electronics", listOf("magnet", "electromagnet")),
        HsnEntry("8506", "Primary cells, batteries", 18.0, "Electronics", listOf("battery", "cell", "dry cell", "button cell")),
        HsnEntry("8507", "Accumulators, rechargeable batteries", 18.0, "Electronics", listOf("battery", "rechargeable", "lithium", "lead acid", "inverter battery")),
        HsnEntry("8508", "Vacuum cleaners", 18.0, "Appliance", listOf("vacuum cleaner", "vacuum")),
        HsnEntry("8509", "Electromechanical domestic appliances", 18.0, "Appliance", listOf("mixer", "grinder", "juicer", "blender", "food processor")),
        HsnEntry("8510", "Shavers, hair clippers", 18.0, "Appliance", listOf("shaver", "trimmer", "hair clipper", "epilator")),
        HsnEntry("8511", "Ignition equipment", 18.0, "Automobile", listOf("spark plug", "ignition")),
        HsnEntry("8512", "Lighting equipment", 18.0, "Electronics", listOf("headlight", "indicator", "lamp", "torch", "flashlight")),
        HsnEntry("8513", "Portable electric lamps", 18.0, "Electronics", listOf("torch", "flashlight", "lantern")),
        HsnEntry("8514", "Electric furnaces, ovens", 18.0, "Appliance", listOf("oven", "furnace", "microwave", "toaster", "air fryer")),
        HsnEntry("8515", "Electric soldering equipment", 18.0, "Appliance", listOf("soldering iron", "welder")),
        HsnEntry("8516", "Electric water/space heaters", 18.0, "Appliance", listOf("heater", "geyser", "water heater", "immersion rod", "room heater")),
        HsnEntry("8517", "Telephones, smartphones", 18.0, "Electronics", listOf("phone", "mobile", "smartphone", "landline", "telephone")),
        HsnEntry("8518", "Microphones, speakers, headphones", 18.0, "Electronics", listOf("speaker", "headphone", "earphone", "earbud", "mic", "airpods")),
        HsnEntry("8519", "Sound recording equipment", 18.0, "Electronics", listOf("recorder", "turntable")),
        HsnEntry("8520", "Magnetic tape recorders", 18.0, "Electronics", listOf("tape", "recorder")),
        HsnEntry("8521", "Video recording equipment", 18.0, "Electronics", listOf("camera", "cctv", "dvr", "nvr", "video recorder")),
        HsnEntry("8522", "Parts for sound/video equipment", 18.0, "Electronics", listOf("speaker part", "camera part")),
        HsnEntry("8523", "Discs, tapes, storage media", 18.0, "Electronics", listOf("cd", "dvd", "usb", "pen drive", "memory card", "hard disk", "ssd")),
        HsnEntry("8524", "Flat panel displays", 18.0, "Electronics", listOf("lcd", "led", "monitor", "display")),
        HsnEntry("8525", "Transmission apparatus", 18.0, "Electronics", listOf("radio", "television", "tv", "antenna", "set top box")),
        HsnEntry("8526", "Radar equipment", 18.0, "Electronics", listOf("radar", "gps", "navigation")),
        HsnEntry("8527", "Reception apparatus", 18.0, "Electronics", listOf("radio", "receiver", "tuner")),
        HsnEntry("8528", "Monitors, projectors, TVs", 18.0, "Electronics", listOf("tv", "television", "monitor", "projector", "led tv", "smart tv", "oled")),
        HsnEntry("8529", "Parts for monitors/TVs", 18.0, "Electronics", listOf("screen", "panel", "display part")),
        HsnEntry("8530", "Signalling equipment", 18.0, "Electronics", listOf("traffic light", "signal")),
        HsnEntry("8531", "Electric sound/visual signalling", 18.0, "Electronics", listOf("alarm", "buzzer", "bell", "siren")),
        HsnEntry("8532", "Capacitors", 18.0, "Electronics", listOf("capacitor", "condenser")),
        HsnEntry("8533", "Resistors", 18.0, "Electronics", listOf("resistor", "rheostat")),
        HsnEntry("8534", "Printed circuits", 18.0, "Electronics", listOf("pcb", "circuit board")),
        HsnEntry("8535", "Electrical switches >1000V", 18.0, "Electronics", listOf("switch", "circuit breaker", "fuse")),
        HsnEntry("8536", "Electrical switches <1000V", 18.0, "Electronics", listOf("switch", "socket", "plug", "relay", "contactor", "mcb", "mcbr")),
        HsnEntry("8537", "Control panels", 18.0, "Electronics", listOf("panel", "control", "switchboard")),
        HsnEntry("8538", "Parts for switches/panels", 18.0, "Electronics", listOf("panel part", "switch part")),
        HsnEntry("8539", "Electric lamps", 18.0, "Electronics", listOf("bulb", "tube light", "cfl", "led bulb", "panel light", "downlight")),
        HsnEntry("8540", "Thermionic cathode tubes", 18.0, "Electronics", listOf("valve", "tube")),
        HsnEntry("8541", "Semiconductor devices", 18.0, "Electronics", listOf("diode", "transistor", "solar cell", "led", "photovoltaic")),
        HsnEntry("8542", "Electronic integrated circuits", 18.0, "Electronics", listOf("chip", "processor", "ic", "cpu", "gpu", "microprocessor")),
        HsnEntry("8543", "Electrical machines n.e.s.", 18.0, "Electronics", listOf("xray", "ultrasonic")),
        HsnEntry("8544", "Insulated wire, cable", 18.0, "Electronics", listOf("wire", "cable", "harness", "coaxial", "fibre optic")),
        HsnEntry("8545", "Carbon electrodes", 18.0, "Electronics", listOf("electrode", "brush", "carbon")),
        HsnEntry("8546", "Insulators", 18.0, "Electronics", listOf("insulator", "porcelain")),
        HsnEntry("8547", "Insulating fittings", 18.0, "Electronics", listOf("fitting", "insulator")),
        HsnEntry("8548", "Electrical parts n.e.s.", 18.0, "Electronics", listOf("battery pack", "capacitor part")),
        HsnEntry("8701", "Tractors", 18.0, "Automobile", listOf("tractor", "farm tractor")),
        HsnEntry("8702", "Motor vehicles for transport", 18.0, "Automobile", listOf("bus", "truck", "minibus")),
        HsnEntry("8703", "Cars, SUVs, motorcycles", 18.0, "Automobile", listOf("car", "suv", "sedan", "hatchback", "bike", "motorcycle", "scooter", "auto rickshaw")),
        HsnEntry("8704", "Dumpers, lorries", 18.0, "Automobile", listOf("truck", "dumper", "lorry", "tipper")),
        HsnEntry("8705", "Special purpose motor vehicles", 18.0, "Automobile", listOf("ambulance", "crane", "fire engine")),
        HsnEntry("8706", "Chassis with engine", 18.0, "Automobile", listOf("chassis")),
        HsnEntry("8707", "Bodies for motor vehicles", 18.0, "Automobile", listOf("body", "cabin")),
        HsnEntry("8708", "Parts for motor vehicles", 18.0, "Automobile", listOf("part", "bumper", "mirror", "windscreen", "brake pad", "clutch plate", "filter", "gasket")),
        HsnEntry("8709", "Work trucks", 18.0, "Automobile", listOf("forklift", "work truck")),
        HsnEntry("8711", "Motorcycles, scooters", 18.0, "Automobile", listOf("motorcycle", "bike", "scooter", "moped")),
        HsnEntry("8712", "Bicycles", 18.0, "Automobile", listOf("bicycle", "cycle", "tricycle")),
        HsnEntry("8713", "Invalid carriages", 18.0, "Automobile", listOf("wheelchair", "invalid carriage")),
        HsnEntry("8714", "Parts for bicycles", 18.0, "Automobile", listOf("bicycle part", "chain", "pedal")),
        HsnEntry("8715", "Baby carriages", 18.0, "Automobile", listOf("stroller", "pram", "baby carriage")),
        HsnEntry("8716", "Trailers, semi-trailers", 18.0, "Automobile", listOf("trailer", "semi trailer", "container")),
        HsnEntry("9001", "Optical fibres, lenses", 18.0, "Electronics", listOf("lens", "spectacles", "goggles", "contact lens")),
        HsnEntry("9002", "Optical elements", 18.0, "Electronics", listOf("mirror", "prism", "filter")),
        HsnEntry("9003", "Frames for spectacles", 18.0, "Electronics", listOf("frame", "spectacles frame")),
        HsnEntry("9004", "Spectacles, goggles", 18.0, "Electronics", listOf("glasses", "sunglasses", "goggles")),
        HsnEntry("9005", "Binoculars", 18.0, "Electronics", listOf("binoculars", "telescope")),
        HsnEntry("9006", "Photographic cameras", 18.0, "Electronics", listOf("camera", "dslr", "mirrorless")),
        HsnEntry("9007", "Cinematographic cameras", 18.0, "Electronics", listOf("video camera", "camcorder")),
        HsnEntry("9008", "Projectors", 18.0, "Electronics", listOf("projector", "slide projector")),
        HsnEntry("9010", "Photo laboratory apparatus", 18.0, "Electronics", listOf("darkroom", "enlarger")),
        HsnEntry("9011", "Optical microscopes", 18.0, "Electronics", listOf("microscope")),
        HsnEntry("9012", "Microscopes n.e.s.", 18.0, "Electronics", listOf("microscope")),
        HsnEntry("9013", "Liquid crystal devices", 18.0, "Electronics", listOf("lcd", "laser")),
        HsnEntry("9014", "Surveying instruments", 18.0, "Electronics", listOf("theodolite", "level")),
        HsnEntry("9015", "Drawing, measuring instruments", 18.0, "Electronics", listOf("compass", "ruler", "divider")),
        HsnEntry("9016", "Balances", 18.0, "Electronics", listOf("balance", "scale")),
        HsnEntry("9017", "Drafting, measuring instruments", 18.0, "Electronics", listOf("draughting", "measuring tape")),
        HsnEntry("9018", "Medical instruments", 18.0, "Medical", listOf("syringe", "needle", "catheter", "instrument")),
        HsnEntry("9019", "Mechano-therapy appliances", 18.0, "Medical", listOf("massage", "physiotherapy")),
        HsnEntry("9020", "Breathing appliances", 18.0, "Medical", listOf("oxygen mask", "respirator")),
        HsnEntry("9021", "Orthopaedic appliances", 18.0, "Medical", listOf("splint", "prosthesis", "brace")),
        HsnEntry("9022", "X-ray apparatus", 18.0, "Medical", listOf("xray", "x-ray")),
        HsnEntry("9023", "Instruments for demonstration", 18.0, "Medical", listOf("demo", "training")),
        HsnEntry("9024", "Testing machines (hardness)", 18.0, "Appliance", listOf("hardness tester", "tensile")),
        HsnEntry("9025", "Thermometers, barometers", 18.0, "Electronics", listOf("thermometer", "barometer", "hygrometer")),
        HsnEntry("9026", "Flow meters", 18.0, "Electronics", listOf("flow meter", "level gauge")),
        HsnEntry("9027", "Physical/chemical analysis instruments", 18.0, "Electronics", listOf("spectrophotometer", "chromatograph", "ph meter")),
        HsnEntry("9028", "Gas meters, liquid meters", 18.0, "Electronics", listOf("gas meter", "water meter")),
        HsnEntry("9029", "Speed indicators, tachometers", 18.0, "Electronics", listOf("odometer", "speedometer")),
        HsnEntry("9030", "Oscilloscopes, analysers", 18.0, "Electronics", listOf("oscilloscope", "multimeter", "tester")),
        HsnEntry("9031", "Measuring instruments n.e.s.", 18.0, "Electronics", listOf("gauge", "caliper", "micrometer")),
        HsnEntry("9032", "Automatic regulating instruments", 18.0, "Electronics", listOf("thermostat", "regulator", "timer")),
        HsnEntry("9101", "Wrist watches", 18.0, "Watch", listOf("watch", "wristwatch", "smartwatch")),
        HsnEntry("9102", "Wrist watches (other)", 18.0, "Watch", listOf("watch")),
        HsnEntry("9103", "Clocks with watch movements", 18.0, "Watch", listOf("clock", "desk clock")),
        HsnEntry("9104", "Dashboard clocks", 18.0, "Watch", listOf("car clock", "dashboard")),
        HsnEntry("9105", "Other clocks", 18.0, "Watch", listOf("wall clock", "alarm clock", "clock")),
        HsnEntry("9106", "Time registers, recorders", 18.0, "Watch", listOf("time recorder", "punch clock")),
        HsnEntry("9107", "Time switches", 18.0, "Electronics", listOf("timer", "time switch")),
        HsnEntry("9108", "Watch movements", 18.0, "Watch", listOf("movement", "mechanism")),
        HsnEntry("9109", "Clock movements", 18.0, "Watch", listOf("clock movement")),
        HsnEntry("9110", "Complete watch/clock movements", 18.0, "Watch", listOf("complete movement")),
        HsnEntry("9111", "Watch cases", 18.0, "Watch", listOf("watch case", "strap")),
        HsnEntry("9112", "Clock cases", 18.0, "Watch", listOf("clock case")),
        HsnEntry("9113", "Watch bands, straps", 18.0, "Watch", listOf("strap", "band", "bracelet")),
        HsnEntry("9114", "Other watch/clock parts", 18.0, "Watch", listOf("crown", "hand", "dial")),
        HsnEntry("9401", "Seats, chairs, sofas", 18.0, "Furniture", listOf("chair", "sofa", "seat", "stool", "bench", "recliner")),
        HsnEntry("9402", "Medical furniture", 18.0, "Furniture", listOf("hospital bed", "operating table", "dentist chair")),
        HsnEntry("9403", "Other furniture", 18.0, "Furniture", listOf("table", "desk", "shelf", "cupboard", "almirah", "bed", "wardrobe", "cabinet", "dining table")),
        HsnEntry("9404", "Mattresses, cushions", 18.0, "Furniture", listOf("mattress", "cushion", "pillow", "sleeping bag")),
        HsnEntry("9501", "Tricycles, scooters, pedal cars", 18.0, "Toys", listOf("tricycle", "scooter", "toy")),
        HsnEntry("9502", "Dolls, toy animals", 18.0, "Toys", listOf("doll", "teddy", "toy animal")),
        HsnEntry("9503", "Toys n.e.s.", 18.0, "Toys", listOf("toy", "puzzle", "board game", "lego", "car toy")),
        HsnEntry("9504", "Video game consoles, boards", 18.0, "Electronics", listOf("playstation", "xbox", "nintendo", "chess", "carrom")),
        HsnEntry("9505", "Festive, carnival articles", 18.0, "Toys", listOf("diwali", "christmas", "decoration")),
        HsnEntry("9506", "Sports equipment", 18.0, "Sports", listOf("cricket bat", "football", "tennis", "golf", "yoga mat", "gym")),
        HsnEntry("9507", "Fishing rods, nets", 18.0, "Sports", listOf("fishing", "rod", "net")),
        HsnEntry("9508", "Roundabouts, swings", 18.0, "Sports", listOf("swing", "slide", "merry go round")),
        HsnEntry("9601", "Worked ivory, bone, shell", 18.0, "Handicraft", listOf("ivory", "bone", "shell")),
        HsnEntry("9602", "Worked vegetable material", 18.0, "Handicraft", listOf("cork", "straw")),
        HsnEntry("9612", "Typewriter ribbons, ink pads", 18.0, "Stationery", listOf("ribbon", "ink pad")),
        HsnEntry("9613", "Cigarette lighters, parts", 18.0, "Handicraft", listOf("lighter", "flint")),
        HsnEntry("9616", "Scent sprays, powder-puffs", 18.0, "Cosmetics", listOf("perfume spray", "powder puff")),
        HsnEntry("9617", "Vacuum flasks, parts", 18.0, "Handicraft", listOf("thermos", "flask")),
        HsnEntry("9618", "Tailors' dummies", 18.0, "Handicraft", listOf("mannequin", "dummy")),
        HsnEntry("9619", "Sanitary towels, diapers", 18.0, "Pharma", listOf("pad", "diaper", "nappy", "sanitary")),
        HsnEntry("9620", "Mounts, bases for cameras", 18.0, "Electronics", listOf("tripod", "mount", "stand")),

        // ========== GST 28% ==========
        HsnEntry("2202", "Aerated drinks, sweetened", 28.0, "Food", listOf("cola", "sprite", "pepsi", "coke", "thums up")),
        HsnEntry("2203", "Beer", 28.0, "Food", listOf("beer", "kingfisher", "tuborg")),
        HsnEntry("2204", "Wine of fresh grapes", 28.0, "Food", listOf("wine", "red wine", "white wine")),
        HsnEntry("2205", "Vermouth", 28.0, "Food", listOf("vermouth")),
        HsnEntry("2206", "Other fermented beverages", 28.0, "Food", listOf("sake", "mead")),
        HsnEntry("2207", "Undenatured ethyl alcohol", 28.0, "Food", listOf("ethanol", "spirits")),
        HsnEntry("2208", "Spirits, liqueurs", 28.0, "Food", listOf("whisky", "rum", "vodka", "brandy", "gin", "tequila")),
        HsnEntry("2401", "Tobacco", 28.0, "Tobacco", listOf("tobacco", "cigarette", "beedi", "pan masala")),
        HsnEntry("2402", "Cigars, cigarettes", 28.0, "Tobacco", listOf("cigar", "cigarette")),
        HsnEntry("2403", "Other tobacco preparations", 28.0, "Tobacco", listOf("pan masala", "gutka", "zarda", "snuff")),
        HsnEntry("3004", "Medicaments (patented)", 28.0, "Pharma", listOf("patented medicine")),
        HsnEntry("3304", "Make-up, lip, eye preparations", 28.0, "Cosmetics", listOf("lipstick", "mascara", "foundation", "makeup", "kajal", "eyeliner")),
        HsnEntry("3305", "Shampoos, hair preparations", 28.0, "Cosmetics", listOf("shampoo", "hair oil", "hair dye", "conditioner")),
        HsnEntry("3307", "Deodorants, perfumes", 28.0, "Cosmetics", listOf("deodorant", "perfume", "body spray")),
        HsnEntry("3401", "Soap (toilet)", 28.0, "Cosmetics", listOf("toilet soap", "lux", "dove")),
        HsnEntry("3924", "Plastic tableware, kitchenware", 28.0, "Plastic", listOf("plate", "cup", "spoon", "fork", "knife")),
        HsnEntry("3950", "Plastic articles for conveyance", 28.0, "Plastic", listOf("plastic pipe", "plastic sheet")),
        HsnEntry("4011", "New pneumatic rubber tyres", 28.0, "Automobile", listOf("car tyre", "bike tyre", "truck tyre")),
        HsnEntry("6403", "Leather footwear (sports)", 28.0, "Footwear", listOf("sport shoe", "running shoe")),
        HsnEntry("7106", "Silver", 28.0, "Jewellery", listOf("silver", "chandi")),
        HsnEntry("7107", "Gold", 3.0, "Jewellery", listOf("gold", "sona")),
        HsnEntry("7108", "Platinum", 3.0, "Jewellery", listOf("platinum")),
        HsnEntry("7113", "Articles of jewellery", 3.0, "Jewellery", listOf("jewelry", "ring", "necklace", "bangle", "gold", "silver", "diamond")),
        HsnEntry("7116", "Articles of natural pearls", 3.0, "Jewellery", listOf("pearl", "moti")),
        HsnEntry("9401", "Seats in motor vehicles", 28.0, "Automobile", listOf("car seat", "vehicle seat")),
        HsnEntry("9405", "Luminaires, lighting fittings", 28.0, "Electronics", listOf("chandelier", "pendant light", "spot light")),

        // ========== CONSTRUCTION MATERIALS (18%) ==========
        HsnEntry("2523", "Cement", 28.0, "Construction", listOf("cement", "opc", "ppc", "ultratech", "ambuja")),
        HsnEntry("2524", "Asbestos", 18.0, "Construction", listOf("asbestos")),
        HsnEntry("2618", "Slag", 18.0, "Construction", listOf("slag", "granulated")),
        HsnEntry("6810", "Articles of cement", 18.0, "Construction", listOf("brick", "tile", "slab", "block")),
        HsnEntry("6901", "Bricks of siliceous earth", 18.0, "Construction", listOf("brick", "fire brick")),
        HsnEntry("6902", "Bricks of refractory earth", 18.0, "Construction", listOf("refractory brick")),
        HsnEntry("6903", "Other refractory articles", 18.0, "Construction", listOf("crucible", "retort")),
        HsnEntry("6904", "Ceramic building bricks", 18.0, "Construction", listOf("brick", "hollow brick")),
        HsnEntry("6905", "Roofing tiles, chimney pots", 18.0, "Construction", listOf("tile", "roof tile", "terracotta")),
        HsnEntry("6907", "Ceramic tiles", 28.0, "Construction", listOf("tile", "floor tile", "wall tile", "vitrified tile", "ceramic")),
        HsnEntry("6908", "Glazed tiles", 28.0, "Construction", listOf("glazed tile")),
        HsnEntry("6909", "Ceramic articles for laboratory", 18.0, "Construction", listOf("crucible", "pot")),
        HsnEntry("6910", "Ceramic sanitary fixtures", 18.0, "Construction", listOf("wash basin", "sink", "toilet")),
        HsnEntry("6911", "Ceramic tableware", 18.0, "Construction", listOf("cup", "plate", "bowl")),
        HsnEntry("6912", "Ceramic articles n.e.s.", 18.0, "Construction", listOf("vase", "figurine")),

        // ========== STATIONERY & OFFICE (18%) ==========
        HsnEntry("3212", "Printing inks", 18.0, "Stationery", listOf("ink", "printer ink")),
        HsnEntry("3213", "Artists' colours, paints", 18.0, "Stationery", listOf("paint", "watercolour", "acrylic")),
        HsnEntry("3214", "Putty, fillers", 18.0, "Construction", listOf("putty", "sealant", "grout")),
        HsnEntry("3702", "Photographic film", 18.0, "Stationery", listOf("film", "negative")),
        HsnEntry("3703", "Photographic paper", 18.0, "Stationery", listOf("photo paper", "printing paper")),
        HsnEntry("4420", "Wood marquetry, frames", 18.0, "Furniture", listOf("frame", "mirror frame", "photo frame")),
        HsnEntry("4421", "Other wood articles", 18.0, "Furniture", listOf("wood", "clothes peg")),
        HsnEntry("4802", "Uncoated paper for writing", 18.0, "Stationery", listOf("writing paper", "notebook paper")),
        HsnEntry("4810", "Coated paper for printing", 18.0, "Stationery", listOf("glossy paper", "magazine paper")),
        HsnEntry("4811", "Paper coated, impregnated", 18.0, "Stationery", listOf("wax paper", "carbon paper")),
        HsnEntry("4816", "Carbon paper, duplicating paper", 18.0, "Stationery", listOf("carbon paper", "stencil")),
        HsnEntry("4817", "Envelopes, letter cards", 18.0, "Stationery", listOf("envelope", "letter")),
        HsnEntry("4818", "Toilet tissue, tissues", 18.0, "Stationery", listOf("tissue", "napkin", "toilet paper", "wet wipes")),
        HsnEntry("4819", "Cartons, boxes of paper", 18.0, "Stationery", listOf("box", "carton", "gift box")),
        HsnEntry("4820", "Registers, notebooks, diaries", 18.0, "Stationery", listOf("notebook", "register", "diary", "copy")),
        HsnEntry("4821", "Paper labels, printed", 18.0, "Stationery", listOf("label", "sticker", "price tag")),
        HsnEntry("4823", "Other articles of paper", 18.0, "Stationery", listOf("paper cup", "paper plate", "paper bag")),
        HsnEntry("4901", "Printed books, brochures", 18.0, "Stationery", listOf("book", "brochure", "textbook", "notebook")),
        HsnEntry("4902", "Newspapers, journals, periodicals", 18.0, "Stationery", listOf("newspaper", "magazine", "journal")),
        HsnEntry("4903", "Children's picture books", 18.0, "Stationery", listOf("colouring book", "picture book")),
        HsnEntry("4904", "Music printed or in manuscript", 18.0, "Stationery", listOf("sheet music")),
        HsnEntry("4905", "Maps, hydrographic charts", 18.0, "Stationery", listOf("map", "atlas")),
        HsnEntry("4906", "Drawings, plans", 18.0, "Stationery", listOf("blueprint", "plan")),
        HsnEntry("4907", "Stamps, cheque books, banknotes", 18.0, "Stationery", listOf("stamp", "cheque", "banknote")),
        HsnEntry("4908", "Transfers (decalcomanias)", 18.0, "Stationery", listOf("decal", "transfer sticker")),
        HsnEntry("4909", "Printed or illustrated cards", 18.0, "Stationery", listOf("greeting card", "wedding card", "visiting card", "business card")),
        HsnEntry("4910", "Calendars", 18.0, "Stationery", listOf("calendar", "desk calendar", "wall calendar")),
        HsnEntry("4911", "Other printed matter", 18.0, "Stationery", listOf("poster", "leaflet", "catalogue", "manual")),
        HsnEntry("8305", "Fittings for loose-leaf binders", 18.0, "Stationery", listOf("binder", "clip")),
        HsnEntry("8311", "Wire, rods for soldering", 18.0, "Stationery", listOf("solder", "wire")),
        HsnEntry("9608", "Pens, pencils, markers", 18.0, "Stationery", listOf("pen", "pencil", "marker", "highlighter", "ballpoint", "gel pen")),
        HsnEntry("9609", "Pencils, crayons", 18.0, "Stationery", listOf("pencil", "crayon", "coloured pencil")),
        HsnEntry("9610", "Chalkboards, slates", 18.0, "Stationery", listOf("blackboard", "whiteboard", "chalkboard")),
        HsnEntry("9611", "Date, sealing stamps", 18.0, "Stationery", listOf("stamp", "seal", "date stamp")),
        HsnEntry("9612", "Typewriter/printer ribbons", 18.0, "Stationery", listOf("ribbon", "ink ribbon")),
        HsnEntry("9613", "Cigarette lighters", 18.0, "Stationery", listOf("lighter")),
        HsnEntry("9614", "Smoking pipes", 18.0, "Stationery", listOf("pipe", "hookah")),
        HsnEntry("9615", "Combs, hair-slides", 18.0, "Stationery", listOf("comb", "hair clip", "bobby pin")),
        HsnEntry("9616", "Scent sprays, powder-puffs", 18.0, "Stationery", listOf("perfume bottle", "powder puff")),
        HsnEntry("9617", "Vacuum flasks", 18.0, "Stationery", listOf("thermos", "insulated bottle")),
        HsnEntry("9618", "Tailors' dummies", 18.0, "Stationery", listOf("mannequin")),
        HsnEntry("9619", "Sanitary towels, pads, tampons", 18.0, "Stationery", listOf("sanitary pad", "tampon", "diaper")),
        HsnEntry("9620", "Mounts, bases for cameras", 18.0, "Stationery", listOf("tripod", "camera mount"))
    )

    fun search(query: String): List<HsnEntry> {
        if (query.isBlank()) return emptyList()
        val q = query.trim().lowercase()
        return masterList.filter { entry ->
            entry.code.contains(q) ||
            entry.description.lowercase().contains(q) ||
            entry.keywords.any { it.lowercase().contains(q) }
        }.sortedBy { it.code }
    }

    fun suggestForItem(itemName: String): List<HsnEntry> {
        if (itemName.isBlank()) return emptyList()
        val words = itemName.lowercase().split("\\s+".toRegex())
        return masterList.filter { entry ->
            words.any { word ->
                entry.keywords.any { kw -> kw.lowercase().contains(word) || word.contains(kw.lowercase()) } ||
                entry.description.lowercase().contains(word)
            }
        }.sortedByDescending { entry ->
            words.count { word ->
                entry.keywords.any { kw -> kw.lowercase().contains(word) || word.contains(kw.lowercase()) }
            }
        }.take(5)
    }

    fun getTaxRate(hsnCode: String): Double {
        val clean = hsnCode.trim()
        val exact = masterList.find { it.code == clean }
        if (exact != null) return exact.taxRate
        return when {
            clean.startsWith("0") || clean.startsWith("1") || clean.startsWith("2") -> {
                if (clean.startsWith("09") || clean.startsWith("10") || clean.startsWith("11") ||
                    clean.startsWith("12") || clean.startsWith("15") || clean.startsWith("17")) 0.0
                else if (clean.startsWith("04") || clean.startsWith("07") || clean.startsWith("08")) 5.0
                else 18.0
            }
            clean.startsWith("71") -> 3.0
            clean.startsWith("22") && clean.startsWith("220") -> 28.0
            clean.startsWith("24") || clean.startsWith("2523") -> 28.0
            clean.startsWith("2201") || clean.startsWith("2202") -> 12.0
            else -> 18.0
        }
    }

    fun getCategory(hsnCode: String): String {
        return masterList.find { it.code == hsnCode.trim() }?.category ?: "Unknown"
    }

    fun getAllCategories(): List<String> = masterList.map { it.category }.distinct().sorted()

    fun getByCategory(category: String): List<HsnEntry> = masterList.filter { it.category == category }.sortedBy { it.code }

    fun getCount(): Int = masterList.size
}
